apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cargo-tracker-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: cargo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cargo-tracker-service
                port:
                  number: 80